---
- name: "[Local] dp_modify"
  block:
  - name: "[Local] config_save"
    local_action:
      module: "datapower"
      actions:
      - action: "config_save"
      connect:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        user: "{{ ansible_user }}"
        passwd: "{{ ansible_password }}"
        domain: "{{ ansible_domain }}"
  - name: "[Local] config_update"
    local_action:
      module: "datapower"
      actions:
      - action: "config_create"
      - action: "config_modify"
      - action: "config_delete"
      connect:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        user: "{{ ansible_user }}"
        passwd: "{{ ansible_password }}"
        domain: "{{ ansible_domain }}"
      options:
        policy: "{{ ansible_policy }}"
  - name: "[Local] config_save"
    local_action:
      module: "datapower"
      actions:
      - action: "config_save"
      connect:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        user: "{{ ansible_user }}"
        passwd: "{{ ansible_password }}"
        domain: "{{ ansible_domain }}"
  when:
  - "((ansible_policy is defined))"
