---
- name: "[Local] dp_backup"
  block:
  - name: "[Local] backup_create"
    local_action:
      module: "datapower"
      actions:
      - action: "config_save"
      - action: "backup_create"
      connect:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        user: "{{ ansible_user }}"
        passwd: "{{ ansible_password }}"
        domain: "{{ ansible_domain }}"
  when:
  - "((ansible_domain is defined))"
